### ISSUE TITLE
[v0.2.1] SQLite3::CantOpenException: unable to open database file

### ISSUE THREAD

**Issue by adrienpoly** [oldmoe/litestack#11]
Hello 

Thanks for your work on this Gem, very excited about it.
On a test project, I upgraded from 0.1.8 to 0.2.1 and I am getting this error whenever I try to start the app
```
SQLite3::CantOpenException: unable to open database file
```

It is a blank project using Rails 7.1 (main)

<details>
<summary>here is the stack trace</summary>
rails s
/Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.2-arm64-darwin/lib/sqlite3/database.rb:90:in `open_v2': unable to open database file (SQLite3::CantOpenException)
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.2-arm64-darwin/lib/sqlite3/database.rb:90:in `initialize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:284:in `new'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:284:in `create_connection'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litequeue.rb:109:in `create_connection'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:279:in `block in create_pooled_connection'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:146:in `block (2 levels) in initialize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:115:in `block in synchronize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:115:in `synchronize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:115:in `synchronize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:146:in `block in initialize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:145:in `times'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:145:in `initialize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:279:in `new'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:279:in `create_pooled_connection'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:252:in `setup'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litejobqueue.rb:153:in `setup'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:218:in `init'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litequeue.rb:40:in `initialize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litejobqueue.rb:73:in `initialize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litejobqueue.rb:63:in `new'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litejobqueue.rb:57:in `block in jobqueue'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:115:in `block in synchronize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:115:in `synchronize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:115:in `synchronize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litesupport.rb:91:in `synchronize'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litejobqueue.rb:57:in `jobqueue'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litejob.rb:89:in `get_jobqueue'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack/litejob.rb:46:in `included'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/active_job/queue_adapters/litejob_adapter.rb:43:in `include'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/active_job/queue_adapters/litejob_adapter.rb:43:in `<class:Job>'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/active_job/queue_adapters/litejob_adapter.rb:32:in `<class:LitejobAdapter>'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/active_job/queue_adapters/litejob_adapter.rb:14:in `<module:QueueAdapters>'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/active_job/queue_adapters/litejob_adapter.rb:9:in `<module:ActiveJob>'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/active_job/queue_adapters/litejob_adapter.rb:8:in `<main>'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack.rb:17:in `require_relative'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/litestack-0.2.1/lib/litestack.rb:17:in `<main>'
        from <internal:/Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `each'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `block in require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `each'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler.rb:196:in `require'
        from /Users/adrien/code/projects/maneki/config/application.rb:19:in `<main>'
        from <internal:/Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/commands/server/server_command.rb:139:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/commands/server/server_command.rb:136:in `perform'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/command/base.rb:179:in `invoke_command'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/command/base.rb:74:in `perform'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/command.rb:71:in `block in invoke'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/command.rb:149:in `with_argv'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/command.rb:69:in `invoke'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-80709bfe7a4c/railties/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'

</details>

**Comment by adrienpoly** [comment]
ok looking a bit deeper it looks like I need a db/queue.rb.
I try creating an empty file but without success 
I also looked into changing the path to that db using litejob.yml (both workdir and config) and it seems that neither of those file would allow me to set the `path` to that db file 

hope this can help

**Comment by oldmoe** [comment]
This seems like the library is trying to create the database in a path that doesn't exist. I need to make sure this is properly captured and a more clear error message is reported, but I would love to see your your config files if those exist

**Comment by adrienpoly** [comment]
here is what I have

I tried both in the root of my project and in the config dir

```yml
# config/litejob.yml
path: db/queue.db
queues:
  - [default, 1]
  - [urgent, 5]
  - [critical, 10, "spawn"]
workers: 5 # how many threads/fibers to spawn for queue processing
retries: 5 # how many times to retry a failed job before giving up
retry_delay: 60 # seconds
retry_delay_multiplier: 10 # 60 -> 600 -> 6000 and so on
dead_job_retention: 864000 # 10 days to keep completely faild jobs in the _dead queue
gc_sleep_interval: 7200 # 2 hours of sleep between checking for dead jobs that are ready to be buried forever
logger: STDOUT # possible values are STDOUT, STDERR, NULL or a file location
```
Whatever value I tried in my config file it never updated the path.  So either my file is not correct or it is not read by the gem.

I can start my app if I change in the litestack gem the default path from "../db/queue.db" (outside of the app directory) to "./queue.db". 

hope it can help

**Comment by oldmoe** [comment]
Thanks for sharing more information, that's the problem right these, I will issue a fix soon, thanks again!

**Comment by oldmoe** [comment]
A new version was just pushed, hopefully that fixes the issue

**Comment by adrienpoly** [comment]
Great I’ll test it. Do you have an idea why the path wasn’t picked from the configuration file? How can I override this path ?

**Comment by oldmoe** [comment]
I am looking into that, hopefully there will be another update pushed this weekend

**Comment by oldmoe** [comment]
A fixed version has been pushed, the existing design is not great as you cannot override the null logger in the Rails adapter, but that nit can be fixed later.

**Comment by adrienpoly** [comment]
I could test the latest version and it works great 
thanks
