### ISSUE TITLE
[question] Litestream Configuration Issues

### ISSUE THREAD

**Issue by richjdsmith** [oldmoe/litestack#111]
Has anyone run into odd behaviour between this gem and using Litestream to create real time backups? In particular, I am looking to use the [litestream-ruby](https://github.com/fractaledmind/litestream-ruby) gem and am just looking for any gotchas.

**Comment by misterhtmlcss** [comment]
@richjdsmith a couple thoughts. I'll first acknowledge that this is not a problem I've had to deal with, but I think this may be helpful advice regardless. Sqlite is stored like any other static file on your hard drive and so a simple cron job should be enough to simply copy it and rename it elsewhere on your hard drive. If you are talking about a demolition of your server then you could create another storage bucket and assuming they are within the same network it's probably a relatively simple to set it up in a similar manner as before. I hope this helps.

Let me know if this helps you with your issue or not.

**Comment by oldmoe** [comment]
Principally, there shouldn't be issues between Litestack and Litestream, but that's not a setup we have used (yet) but we will be curious as to what your experience looks like.
