### ISSUE TITLE
How to configure path for Action Cable DB

### ISSUE THREAD

**Issue by adrienpoly** [oldmoe/litestack#14]
Hello 

I am trying to use the Action Cable adapter. 
I need to put the database in `/storage/cable.db` as this is my persisted volume

I have tried to add a litecable.yml file both in the `root` and `config/` with no luck 

here is the WIP PR as the project is open source https://github.com/adrienpoly/rubyvideo/pull/45

thanks

**Comment by fractaledmind** [comment]
Given this line (https://github.com/oldmoe/litestack/blob/57265f62ab1b988731d5ce0d2de2f0f53f2c8fa6/lib/litestack/litesupport.rb#L132), I would expect that setting `ENV["LITESTACK_DATA_PATH"]` to `./storage` would do what you need (move all Livestock databases to the `/storage` directory)

**Comment by oldmoe** [comment]
The way the litecable Rails adapter was setting the configuration was overriding the config found in the .yml file, I found the issue and will push a fix tomorrow, thanks for reporting

**Comment by oldmoe** [comment]
I have pushed the fix, no new gem created yet, please try it out whenever possible, the configuration should be put in ./config/litecable.yml
