### ISSUE TITLE
Litequeue#count doesn't appear to work as expected

### ISSUE THREAD

**Issue by fractaledmind** [oldmoe/litestack#18]
On my machine, the `Litequeue#count` method doesn't work as expected. It always returns the count of the table, even when you pass in a queue name. Below is a reproducible bug script to demonstrate the problem:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "sqlite3"
end

require "sqlite3"

$db = SQLite3::Database.new(":memory:")
$db.execute <<-SQL
  CREATE TABLE queues(
    name TEXT,
    value TEXT
  );
SQL

class WhereIIFTest < Minitest::Test
  def test_where_iif
    $db.execute("INSERT INTO queues(name, value) VALUES (?, ?), (?, ?)", ['default', 1], ['urgent', 10])
    
    where_iif = "SELECT COUNT(*) FROM queues WHERE iif(?, name = ?, 1)"
    
    assert_equal 2, $db.get_first_value(where_iif, nil)
    assert_equal 1, $db.get_first_value(where_iif, 'default')
    assert_equal 1, $db.get_first_value(where_iif, 'urgent')
  end
end
```

**Comment by fractaledmind** [comment]
I found the problem, and there are 2.

Firstly, using `?` to bind arguments requires that you pass as many arguments as `?` in the query. If you only pass 1 argument and use two `?` in the query, only the first `?` gets bound. We need to use named parameters instead to ensure that our 1 argument is bound in both places. 

Secondly, the `iif` function isn't defined quite right, as can be seen:
```irb
> $db.get_first_value("SELECT IIF(:name, 'present', 'blank')", nil)
=> "blank"
> $db.get_first_value("SELECT IIF(:name, 'present', 'blank')", 'urgent')
=> "blank"
```

The first argument to `iif` isn't resolving as is. We need to make it a proper expression. Using `:name IS NULL` works, and only requires that we flip the last two expressions. So, `SELECT COUNT(*) FROM queues WHERE IIF(:name IS NULL, 1, name = :name)` does what we want.

**Comment by oldmoe** [comment]
Yes of course, you are right on both accounts:
This needs to be a positional argument, and the first item need to evaluate to true/false rather than null/not null. I will fix

**Comment by oldmoe** [comment]
This was fixed, though checking on IF NOT NULL
