### ISSUE TITLE
Increase time precision by using UNIXEPOCH('subsec') instead of UNIXEPOCH()

### ISSUE THREAD

**Issue by fractaledmind** [oldmoe/litestack#19]
As of version 3.42.0 (released on 2023-05-16), the `UNIXEPOCH` function now accepts a `subsec` modifier, which "increases the resolution from seconds to milliseconds" (source: https://www.sqlite.org/lang_datefunc.html#subsec). 

By having millisecond precision, instead of only second precision, we allow for finer-grained performance. For example, in tests, everything is slow because a retry will have to wait at least 1 second.

If we want to support up to version 3.37, maybe we should register a custom function that either uses the `'subsec'` modifier with `UNIXEPOCH`, if available, or falls back to the `(JULIANDAY('now') - 2440587.5)*86400.0` function suggested by the docs (source: https://www.sqlite.org/lang_datefunc.html#examples). Either way, I truly believe that millisecond precision is needed.

**Comment by oldmoe** [comment]
It is definitely needed for a better testing experience for litejob, not sure about the value for production but still, it won't hurt (I hope), would you have time to create a PR? or should I go ahead?

**Comment by fractaledmind** [comment]
I'll make a PR tomorrow. You're ok to up the required SQLite version?

**Comment by oldmoe** [comment]
@fractaledmind are you picking up on this? I would like to fix the litejobqueue tests and this can tremendously help, we are already requiring 3.43.0
