### ISSUE TITLE
`hiredis` not in gemspec, attempted to load from `require 'litestack'`.

### ISSUE THREAD

**Issue by ttilberg** [oldmoe/litestack#3]
I was just going to give Litestack a whirl, but it requires `hiredis` in `litestack/litesupport`: https://github.com/oldmoe/litestack/blob/ecf2295b9ac1ee6400d35dc78d79ada34178696b/lib/litestack/litesupport.rb#L2
which itself is required in `litestack.rb`: https://github.com/oldmoe/litestack/blob/3f359f12f75d049c01e6bb14937533b2f1227eef/lib/litestack.rb#L5

Looking through the code, it appears it's used for benchmarks and not actually required by the lib itself.

```
/tmp/litestack-demo
▶ gem install litestack
Successfully installed litestack-0.1.7
Parsing documentation for litestack-0.1.7
Done installing documentation for litestack after 0 seconds
1 gem installed

/tmp/litestack-demo
▶ pry
[1] pry(main)> require 'litestack'
LoadError: cannot load such file -- hiredis
from <internal:/Users/ttilberg/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Caused by LoadError: cannot load such file -- litestack
from <internal:/Users/ttilberg/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
```

**Comment by oldmoe** [comment]
Removed the stray require, thanks for the catch!
