### ISSUE TITLE
Under what condition is Litesupport::Connection forked?

### ISSUE THREAD

**Issue by fractaledmind** [oldmoe/litestack#33]
`Litesupport::Connection` includes the `Forkable` module. I follow why we prepend the `Forkable` module to `Process`, but I don't yet follow how or when `Litesupport::Connection` would be forked and needs to manage that. 

I want to understand the condition(s) so that I can hopefully write tests for these conditions.

**Comment by fractaledmind** [comment]
I guess I don't have a clear picture/understanding yet of how/when the "Rails app is preloaded in the main process before forking children".

**Comment by oldmoe** [comment]
This happens in a server like Falcon (and I guess Puma too) to benefit from copy on write when forking children
