### ISSUE TITLE
0.41 code not published

### ISSUE THREAD

**Issue by adrienpoly** [oldmoe/litestack#42]
I was trying to run #41 to test it and I am getting this error when I start my app

LoadError: cannot load such file -- /Users/adrien/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/litestack-ca27a3d865ee/lib/litestack/litesearch/model

I have the same error running from master

I don't have the error when I use the latest version from RubyGems

I think some code is not published on master as RubyGems version is 0.41 and on master it is 0.40

**Comment by oldmoe** [comment]
Everything should be pushed now, please retry

**Comment by adrienpoly** [comment]
all good

**Comment by mavient** [comment]
It looks like it's still missing the tags, https://github.com/oldmoe/litestack/tags.
