### ISSUE TITLE
Litesearch: has_many through

### ISSUE THREAD

**Issue by AlfonsoUceda** [oldmoe/litestack#45]
Hi! Really nice stack fo sqlite, congratulations.

I've been playing around with it and I'm wondering if Litesearch supports has_many :through associations. I've tried but I failed, all the examples are has_many -> belongs_to.

Cheers

**Comment by oldmoe** [comment]
Hey Alfonso, currently litesearch only supports fetching data from other tables that are:

1. One hop away, thus no has_many :through
2. Identified by a single column match, thus no :polymorphic support

I will be looking into these and check the feasibility of supporting them in the hopefully near future

**Comment by AlfonsoUceda** [comment]
Thanks @oldmoe, no problem just wanted to verify, finally I could search in one table and use the relation to get the desired entities.
