### ISSUE TITLE
Make sure requiring a single Litestack component loads only that component

### ISSUE THREAD

**Issue by oldmoe** [oldmoe/litestack#53]
`require 'litestack'` 

currently loads every component in the library, this is OK, but we should make sure that something like:

`require ''litestack/litecache` 

Will only load the files required to run litecache and not the rest of the library

Same should happen with any configuration that auto loads litestack components like the Rails env configuration like

`config.active_job.queue_adapter = :litejob`

**Comment by goulvench** [comment]
I'd be pretty interested in that! 

I'm currently exploring using SQLite as a dedicated cache for `Rack::Attack` but haven't yet reached a working solution.
- Using native [Rails multi-db](https://guides.rubyonrails.org/v6.1/active_record_multiple_databases.html) (6.1) causes errors as it tries to seed the sqlite database with primary data.
- Using Litestack with default config, when booting Rails creates `db/development/queue.sqlite3` database and tries to run all migrations on it.

I hoped that running…
```shell
bundle add litestack
bin/rails generate litestack:install
```
…would allow writing `Rack::Attack.cache.store = LiteStack::LiteCache.new(path: "...")` in `config/initializers/rack_attack.rb` to have a super-fast cache to throttle bad actors, completely separate from my app's cache and database.

**Comment by oldmoe** [comment]
`bin/rails generate litestack:install`
 Tries to install litestack in every config file possible, don't run it and things should be OK
