### ISSUE TITLE
Remove : Litejob detected an exit, cleaning up

### ISSUE THREAD

**Issue by adrienpoly** [oldmoe/litestack#55]
This is how my test suite report looks 

![CleanShot 2023-10-23 at 14 16 38@2x](https://github.com/oldmoe/litestack/assets/7847244/c8690124-0cdf-4145-8e51-8b7a8c2b9b9b)

would it be possible to either disable those logs in test environment or to redirect them to a standard logger?

https://github.com/oldmoe/litestack/blob/0dbd6194606b71839017bb656ed906602d861888/lib/litestack/litejobqueue.rb#L145

**Comment by westonganger** [comment]
As per this recent commit which has yet to be released, looks like this error message will no longer be displayed when  number of jobs in flight is zero

https://github.com/oldmoe/litestack/commit/ee2eac82ca917c7e96f149f6c782ba9297b10223

Would be nice to have this new change documented in the changelog

**Comment by adrienpoly** [comment]
Thanks 

This being said, there is the `@logger` instance variable available in this class. So maybe `puts` could be replaced by `@logger.info("...")`.

**Comment by oldmoe** [comment]
Yes, this will be removed in the next release if the remaining job count in flight is zero, the main reason to show this on STDOUT is to highlight the reason the process exit is delayed to a manual operator. Logging is optional so there will be cases when the Logger is not available/useful
