### ISSUE TITLE
Not getting ActionCable connected() when using litecable adapter

### ISSUE THREAD

**Issue by westonganger** [oldmoe/litestack#59]
In development when I switch to `adapter: litecable` in `config/cable.yml` then it is not calling the `connected()` function. It does successfully call the `initialized()` function.

Everything works correctly when I switch back to `adapter: async` where I get `connected()` and `received()`

I am using `puma` gem for development server on Rails 7.1. Let me know if there is any other information that would be helpful.

**Comment by adrienpoly** [comment]
I think I had a similar issue but this should be fixed on master by https://github.com/oldmoe/litestack/pull/41

**Comment by westonganger** [comment]
Yup switch to the master branch fixes this. Maybe we could have a new version released that has a functioning LiteCable implementation.

**Comment by westonganger** [comment]
Also would be really helpful to add a changelog entry stating this fix.

**Comment by westonganger** [comment]
@adrienpoly I see that you were trying to add a spec for this in another project https://github.com/adrienpoly/rubyvideo/pull/50 

Would be awesome if maybe we could get a spec for this inside the litestack repo itself.

**Comment by adrienpoly** [comment]
For sure yes I wanted to build a dummy app to add to the project but clearly running out of time right now. I f you can propose something that would be great for sure

**Comment by westonganger** [comment]
Yeah sure, I have the dummy app setup in all my other gems, so I can whip up a PR to get something going.

**Comment by westonganger** [comment]
Added some PRs to resolve a few of these items
- #61
- #62

**Comment by oldmoe** [comment]
I am planning a new release soon that will include all the pending fixes/improvements, just checking what else I can sneak in
