### ISSUE TITLE
Support multi cache reads and writes

### ISSUE THREAD

**Issue by julianrubisch** [oldmoe/litestack#69]
I.e., implement `read_multi_entries`, `write_multi_entries`, and `delete_multi_entries`

@oldmoe I'd be happy to help where I can

**Comment by oldmoe** [comment]
It should be pretty straightforward, I will make that happen while adding proper tests to litecache

**Comment by julianrubisch** [comment]
I think this would also especially benefit from a benchmark, since the gains are usually quite impressive compared to "normal" reads/writes
