### ISSUE TITLE
Implement `delete_matched`

### ISSUE THREAD

**Issue by julianrubisch** [oldmoe/litestack#70]
as per https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-delete_matched

**Comment by oldmoe** [comment]
Delete matched would require having the regex SQLite extension installed, maybe we can detect it and run the matcher only if it exists otherwise return a proper error message. The other option is to try and bundle the extension with Litestack (tricky but probably doable)

**Comment by adrienpoly** [comment]
FYI https://github.com/rails/rails/issues/50443#issuecomment-1882833614

looks like delete_matched could be deprecated in 7.2 et removed in 8.0 so probably best to wait on this issue to resolve before moving forward on that

**Comment by skatkov** [comment]
Plenty of cache stores don't have this method. Is there really a need in that?

**Comment by julianrubisch** [comment]
I agree that if it's deprecated there's no need implementing it. FWIW I always found it handy when developing locally.
