### ISSUE TITLE
Liteboard does not work alongside Rack 3

### ISSUE THREAD

**Issue by rossta** [oldmoe/litestack#83]
After creating a new Rails 7.1 application and running the liteboard executable, 

```
bundle exec liteboard -d path/to/data
```

I see the following error when trying to visit the app at `http://localhost:9292`:

```
NoMethodError: undefined method `unescape' for module URI
```

This error is reproducible with the following dependencies:

Ruby version: 3.3.0
Rails version: 7.1.2
Rack version: 3.0.8
Litestack version: 0.4.2

With this set of dependencies, litestack installs an old version of hanami-router: 0.6.2, whereas the most recent version of hanami-router as of this writing is 2.0.x. The 0.6.x version of hanami-router is not compatible with Ruby 3, hence the error with the URI module. I believe the hanami-router 0.6.x is installed because it [does not constrain the Rack version](https://github.com/hanami/router/blob/0.6.x/hanami-router.gemspec#L22-L24); Bundler happily picks this version to live alongside Rack 3 in my Rails application since [latest version of hanami-router is constrained to Rack 2.x](https://github.com/hanami/router/blob/e0af88dcd3e0ca7acf8c2abc88480b47aa72f3e2/hanami-router.gemspec#L23).

I've [opened an issue with hanami-router to inquire about support for Rack 3](https://github.com/hanami/router/issues/268). In the meantime, a possible fix in Litestack would be to match the rack constraint with `rack ~> 2` or `rack < 3`.

**Comment by rossta** [comment]
For anyone else looking for a workaround, I'm currently downgrading to Rack 2.x in my Rails 7.1 application:

```rb
gem "rack", "~> 2.2" # litestack's liteboard depends on hanami-router which does not currently support rack 3.x as of Dec 2023
```

**Comment by oldmoe** [comment]
This has been fixed in head, hanami-router is removed and liteboard now relies on the rack and rackup gems directly
